<script id="tailwind-config">
      tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "on-tertiary-fixed-variant": "#005049",
                    "on-secondary-fixed": "#341100",
                    "secondary": "#9d4300",
                    "surface": "#f9f9ff",
                    "outline-variant": "#c3c5d7",
                    "tertiary-fixed": "#89f5e7",
                    "surface-container-lowest": "#ffffff",
                    "error": "#ba1a1a",
                    "surface-variant": "#dce2f3",
                    "secondary-fixed": "#ffdbca",
                    "inverse-primary": "#b5c4ff",
                    "surface-bright": "#f9f9ff",
                    "surface-container": "#e7eefe",
                    "background": "#f9f9ff",
                    "inverse-on-surface": "#ebf1ff",
                    "surface-tint": "#1353d8",
                    "surface-dim": "#d3daea",
                    "primary": "#003fb1",
                    "on-primary-fixed": "#00174d",
                    "primary-fixed": "#dbe1ff",
                    "on-error-container": "#93000a",
                    "on-error": "#ffffff",
                    "tertiary": "#00544c",
                    "surface-container-high": "#e2e8f8",
                    "on-primary-container": "#d4dcff",
                    "tertiary-fixed-dim": "#6bd8cb",
                    "on-secondary": "#ffffff",
                    "surface-container-highest": "#dce2f3",
                    "primary-fixed-dim": "#b5c4ff",
                    "on-secondary-fixed-variant": "#783200",
                    "surface-container-low": "#f0f3ff",
                    "on-primary-fixed-variant": "#003dab",
                    "on-surface-variant": "#434654",
                    "inverse-surface": "#2a313d",
                    "on-tertiary-container": "#84f0e2",
                    "on-background": "#151c27",
                    "on-tertiary-fixed": "#00201d",
                    "secondary-fixed-dim": "#ffb690",
                    "outline": "#737686",
                    "tertiary-container": "#006e65",
                    "on-primary": "#ffffff",
                    "on-secondary-container": "#5c2400",
                    "error-container": "#ffdad6",
                    "secondary-container": "#fd761a",
                    "primary-container": "#1a56db",
                    "on-surface": "#151c27",
                    "on-tertiary": "#ffffff",
                    "cta-primary": "#fd761a",
                    "cta-secondary": "#f0f3ff",
                    "text-muted": "#737686",
                    "text-heading": "#151c27"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px"
            },
            "spacing": {
                    "2xl": "48px",
                    "xs": "4px",
                    "container-max": "1280px",
                    "margin-mobile": "16px",
                    "lg": "24px",
                    "md": "16px",
                    "gutter": "24px",
                    "3xl": "64px",
                    "4xl": "96px",
                    "5xl": "128px",
                    "xl": "32px",
                    "sm": "8px",
                    "base": "4px"
            },
            "fontFamily": {
                    "headline-md": ["Inter"],
                    "body-md": ["Inter"],
                    "title-lg": ["Inter"],
                    "label-sm": ["Inter"],
                    "headline-lg-mobile": ["Inter"],
                    "display-xl": ["DM Sans", "Inter"],
                    "display-lg": ["DM Sans", "Inter"],
                    "body-lg": ["Inter"],
                    "headline-lg": ["Inter"],
                    "label-md": ["Inter"]
            },
            "fontSize": {
                    "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                    "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                    "title-lg": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                    "title-md": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
                    "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
                    "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
                    "display-xl": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "display-lg": ["48px", {"lineHeight": "60px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                    "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
                    "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}]
            }
          },
        },
      }
    </script>
